version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 1
      semver-major-days: 7
      semver-minor-days: 3
      semver-patch-days: 1
    ignore:
      - dependency-name: "nx"
      - dependency-name: "@nx/*"
      - dependency-name: "@nestjs/*"
        update-types: [ version-update:semver-major ]
      - dependency-name: "@angular/*"
        update-types: [ version-update:semver-major, version-update:semver-minor ]
      - dependency-name: "@angular-devkit/*"
        update-types: [ version-update:semver-major, version-update:semver-minor ]
      - dependency-name: "@schematics/angular"
        update-types: [ version-update:semver-major, version-update:semver-minor ]
      - dependency-name: "*eslint*"
        update-types: [ version-update:semver-major ]
      - dependency-name: "*jest*"
        update-types: [ version-update:semver-major ]
      - dependency-name: "typescript"
        update-types: [ version-update:semver-major, version-update:semver-minor ]
      # Generally not kept updated by mongoose and minor updates often create problems
      - dependency-name: "mongodb"
        update-types: [ version-update:semver-major, version-update:semver-minor ]
    groups:
      major:
        update-types: [ major ]
      minor-patch:
        update-types: [ minor, patch ]
