version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 1
      semver-major-days: 7
      semver-minor-days: 3
      semver-patch-days: 1
    ignore:
      - dependency-name: "nx"
      - dependency-name: "@nx/*"
      - dependency-name: "@nestjs/*"
      - dependency-name: "@angular/*"
    groups:
      production:
        dependency-type: production
      development:
        dependency-type: development
