version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "nx"
      - dependency-name: "@nx/*"
      - dependency-name: "@nestjs/*"
      - dependency-name: "@angular/*"
    groups:
      production:
        dependency-type: production
      development:
        dependency-type: development
