services:
  database:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - database:/data/db

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.3
    command: [ 'start-dev' ]
    environment:
      KC_HOSTNAME: localhost
      KC_HTTP_RELATIVE_PATH: /auth
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: root
    ports:
      - "8080:8080"
    volumes:
      - ./libs/keycloak:/opt/keycloak/themes/apollusia

volumes:
  database:
