name: Test

on:
  push:
    branches:
        - master
  pull_request:

jobs:
  lint-test:
    name: Lint ${{ matrix.app }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app:
          - frontend
          - frontend-e2e
          - backend
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      # https://github.com/actions/setup-node/issues/480#issuecomment-1915448139
      # https://github.com/nodejs/corepack/issues/612
      - name: Enable Corepack
        run: npm install -g corepack@latest && corepack enable
      - name: Set up Node.js LTS
        uses: actions/setup-node@v5
        with:
          node-version: 24
          cache: 'pnpm'
          cache-dependency-path: pnpm-lock.yaml
      - name: Cache Cypress binary
        if: matrix.app == 'frontend-e2e'
        uses: actions/cache@v4
        with:
          path: ~/.cache/Cypress
          key: cypress-${{ runner.os }}-${{ hashFiles('pnpm-lock.yaml') }}
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Install Cypress binary
        if: matrix.app == 'frontend-e2e'
        run: pnpm exec cypress install
      - name: Lint
        run: pnpm run lint:${{ matrix.app }} --fix
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: 'chore: Fix lint problems'
      - name: Test
        run: pnpm run test:${{ matrix.app }}
